<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OopFactory.X12.FhirConverter</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotLiquid" Version="2.2.692" />
    <PackageReference Include="Hl7.Fhir.R4" Version="5.11.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OopFactory.X12.Core\OopFactory.X12.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\**\*.liquid" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="CodeMappings\*.json" />
  </ItemGroup>

</Project>
