apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fhir-services

resources:
  - ../../base

images:
  - name: PLACEHOLDER_IMAGE
    newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/x12-fhir-converter
    newTag: latest

patches:
  # Production: 3 replicas minimum
  - target:
      kind: Deployment
      name: x12-fhir-converter
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  # Production: higher resource limits
  - target:
      kind: Deployment
      name: x12-fhir-converter
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 1Gi
  # Production HPA: min 3, max 20
  - target:
      kind: HorizontalPodAutoscaler
      name: x12-fhir-converter
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20

configMapGenerator:
  - name: x12-fhir-config
    behavior: merge
    literals:
      - aws-region=us-east-1
      - tenant-table-name=X12FhirConverter-Tenants-production
      - transaction-log-table-name=X12FhirConverter-TransactionLog-production
      - audit-log-table-name=X12FhirConverter-AuditLog-production
