<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OopFactory.X12</RootNamespace>
    <AssemblyName>OopFactory.X12.Core</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Specifications\*.xml" />
    <EmbeddedResource Include="Transformations\*.xslt" />
  </ItemGroup>

</Project>
